# Generated by Django 3.0.8 on 2020-07-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilot',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='pilot',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='pilot',
            old_name='mname',
            new_name='middle_name',
        ),
    ]
