# Generated by Django 3.0.8 on 2020-07-15 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20200714_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='address1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_apt', models.CharField(max_length=4)),
                ('arrival_apt', models.CharField(max_length=4)),
                ('departure_date', models.DateField(verbose_name='departure_date')),
                ('single_engine_time', models.FloatField(default=0)),
                ('multi_engine_time', models.FloatField(default=0)),
                ('rotorcraft_time', models.FloatField(default=0)),
                ('dual_recieved', models.FloatField(default=0)),
                ('pilot_in_command', models.FloatField(default=0)),
                ('second_in_command', models.FloatField(default=0)),
                ('as_flight_instructor', models.FloatField(default=0)),
                ('day_time', models.FloatField(default=0)),
                ('night_time', models.FloatField(default=0)),
                ('x_country_time', models.FloatField(default=0)),
                ('actual_instrument_time', models.FloatField(default=0)),
                ('simulated_instrument_time', models.FloatField(default=0)),
                ('total_duration_of_flight', models.FloatField(default=0)),
                ('number_instrument_approaches', models.IntegerField(default=0)),
                ('number_landings', models.IntegerField(default=0)),
                ('notes_on_flight', models.CharField(max_length=200)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Pilot')),
            ],
        ),
    ]
