# Generated by Django 3.0.8 on 2020-07-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200715_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='actual_instrument_time',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='as_flight_instructor',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='day_time',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='departure_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='dual_recieved',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='multi_engine_time',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='night_time',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='notes_on_flight',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='number_instrument_approaches',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='number_landings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='pilot_in_command',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='rotorcraft_time',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='second_in_command',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='simulated_instrument_time',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='single_engine_time',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='total_duration_of_flight',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='x_country_time',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
